# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
#
# XPU override notes (verified by experiment, see cdist_backward.py):
#   * BLOCK_M=128 dies in TritonXPUUnrollControl with "out of resource:
#     uni_sram" (even with loop_unroll_factor=1); 64 is the widest safe tile.
#   * The j-reduction must stay a serial loop: tl.sum(axis=0) is rejected by
#     the backend and index arithmetic per (i, j) pair is not vectorizable.
import logging
import math

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)

_MAX_BLOCK_M = 64


@libentry()
@triton.jit
def _pdist_backward_p2_kernel(
    grad_ptr,
    x_ptr,
    pdist_ptr,
    out_ptr,
    N,
    M,
    stride_x,
    stride_grad_out,
    BLOCK_M: tl.constexpr,
):
    """Backward kernel for p=2 case (8-way j-unroll, XPU).

    Each program accumulates grad for one row of x over all j != pid_n:
      out[i, :] = sum_{j>i} g_ij * (x_i - x_j) / d_ij
                + sum_{j<i} g_ji * (x_i - x_j) / d_ji
    The 8 independent accumulators batch 8 xj loads + 8 FMA per iteration to
    hide the gm2lm load latency (single-lane-per-core backend, see
    cdist_backward.py for the same technique).
    """
    pid_n = tle.program_id(1)
    pid_m = tle.program_id(0)

    row_offset = pid_n * stride_x
    x_ptr_row = x_ptr + row_offset
    out_ptr_row = out_ptr + pid_n * stride_grad_out

    m_offsets = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    m_mask = m_offsets < M

    x_vals = tl.load(x_ptr_row + m_offsets, mask=m_mask, other=0.0).to(tl.float32)

    acc0 = tl.zeros([BLOCK_M], dtype=tl.float32)
    acc1 = tl.zeros([BLOCK_M], dtype=tl.float32)
    acc2 = tl.zeros([BLOCK_M], dtype=tl.float32)
    acc3 = tl.zeros([BLOCK_M], dtype=tl.float32)
    acc4 = tl.zeros([BLOCK_M], dtype=tl.float32)
    acc5 = tl.zeros([BLOCK_M], dtype=tl.float32)
    acc6 = tl.zeros([BLOCK_M], dtype=tl.float32)
    acc7 = tl.zeros([BLOCK_M], dtype=tl.float32)

    # Pairs where this row is the first index (i, j) with i < j.
    # pdist_idx(j) = pid_n*N - pid_n*(pid_n+1)//2 + (j - pid_n - 1)
    #              = base_idx + j  (linear in j).
    base_idx = pid_n * N - (pid_n * (pid_n + 1)) // 2 - pid_n - 1
    j_start = pid_n + 1
    nmain = (N - j_start) // 8 * 8
    for k in range(0, nmain, 8):
        jj = j_start + k
        xj0 = tl.load(x_ptr + (jj + 0) * stride_x + m_offsets, mask=m_mask, other=0.0).to(tl.float32)
        xj1 = tl.load(x_ptr + (jj + 1) * stride_x + m_offsets, mask=m_mask, other=0.0).to(tl.float32)
        xj2 = tl.load(x_ptr + (jj + 2) * stride_x + m_offsets, mask=m_mask, other=0.0).to(tl.float32)
        xj3 = tl.load(x_ptr + (jj + 3) * stride_x + m_offsets, mask=m_mask, other=0.0).to(tl.float32)
        xj4 = tl.load(x_ptr + (jj + 4) * stride_x + m_offsets, mask=m_mask, other=0.0).to(tl.float32)
        xj5 = tl.load(x_ptr + (jj + 5) * stride_x + m_offsets, mask=m_mask, other=0.0).to(tl.float32)
        xj6 = tl.load(x_ptr + (jj + 6) * stride_x + m_offsets, mask=m_mask, other=0.0).to(tl.float32)
        xj7 = tl.load(x_ptr + (jj + 7) * stride_x + m_offsets, mask=m_mask, other=0.0).to(tl.float32)
        g0 = tl.load(grad_ptr + base_idx + (jj + 0)).to(tl.float32)
        g1 = tl.load(grad_ptr + base_idx + (jj + 1)).to(tl.float32)
        g2 = tl.load(grad_ptr + base_idx + (jj + 2)).to(tl.float32)
        g3 = tl.load(grad_ptr + base_idx + (jj + 3)).to(tl.float32)
        g4 = tl.load(grad_ptr + base_idx + (jj + 4)).to(tl.float32)
        g5 = tl.load(grad_ptr + base_idx + (jj + 5)).to(tl.float32)
        g6 = tl.load(grad_ptr + base_idx + (jj + 6)).to(tl.float32)
        g7 = tl.load(grad_ptr + base_idx + (jj + 7)).to(tl.float32)
        d0 = tl.load(pdist_ptr + base_idx + (jj + 0)).to(tl.float32)
        d1 = tl.load(pdist_ptr + base_idx + (jj + 1)).to(tl.float32)
        d2 = tl.load(pdist_ptr + base_idx + (jj + 2)).to(tl.float32)
        d3 = tl.load(pdist_ptr + base_idx + (jj + 3)).to(tl.float32)
        d4 = tl.load(pdist_ptr + base_idx + (jj + 4)).to(tl.float32)
        d5 = tl.load(pdist_ptr + base_idx + (jj + 5)).to(tl.float32)
        d6 = tl.load(pdist_ptr + base_idx + (jj + 6)).to(tl.float32)
        d7 = tl.load(pdist_ptr + base_idx + (jj + 7)).to(tl.float32)
        diff0 = x_vals - xj0
        diff1 = x_vals - xj1
        diff2 = x_vals - xj2
        diff3 = x_vals - xj3
        diff4 = x_vals - xj4
        diff5 = x_vals - xj5
        diff6 = x_vals - xj6
        diff7 = x_vals - xj7
        acc0 += tl.where(d0 != 0.0, diff0 * g0 / d0, 0.0)
        acc1 += tl.where(d1 != 0.0, diff1 * g1 / d1, 0.0)
        acc2 += tl.where(d2 != 0.0, diff2 * g2 / d2, 0.0)
        acc3 += tl.where(d3 != 0.0, diff3 * g3 / d3, 0.0)
        acc4 += tl.where(d4 != 0.0, diff4 * g4 / d4, 0.0)
        acc5 += tl.where(d5 != 0.0, diff5 * g5 / d5, 0.0)
        acc6 += tl.where(d6 != 0.0, diff6 * g6 / d6, 0.0)
        acc7 += tl.where(d7 != 0.0, diff7 * g7 / d7, 0.0)

    for j in range(j_start + nmain, N):
        xj_vals = tl.load(x_ptr + j * stride_x + m_offsets, mask=m_mask, other=0.0).to(
            tl.float32
        )
        diff = x_vals - xj_vals
        pdist_idx = base_idx + j
        g = tl.load(grad_ptr + pdist_idx).to(tl.float32)
        dist = tl.load(pdist_ptr + pdist_idx).to(tl.float32)
        acc0 += tl.where(dist != 0.0, diff * g / dist, 0.0)

    # Pairs where this row is the second index (j, i) with j < i.
    # pdist_idx(j) = j*N - j*(j+1)//2 + (pid_n - j - 1)  (quadratic in j).
    nmain2 = pid_n // 8 * 8
    for k in range(0, nmain2, 8):
        j0 = k
        s0 = j0
        s1 = j0 + 1
        s2 = j0 + 2
        s3 = j0 + 3
        s4 = j0 + 4
        s5 = j0 + 5
        s6 = j0 + 6
        s7 = j0 + 7
        idx0 = s0 * N - (s0 * (s0 + 1)) // 2 + (pid_n - s0 - 1)
        idx1 = s1 * N - (s1 * (s1 + 1)) // 2 + (pid_n - s1 - 1)
        idx2 = s2 * N - (s2 * (s2 + 1)) // 2 + (pid_n - s2 - 1)
        idx3 = s3 * N - (s3 * (s3 + 1)) // 2 + (pid_n - s3 - 1)
        idx4 = s4 * N - (s4 * (s4 + 1)) // 2 + (pid_n - s4 - 1)
        idx5 = s5 * N - (s5 * (s5 + 1)) // 2 + (pid_n - s5 - 1)
        idx6 = s6 * N - (s6 * (s6 + 1)) // 2 + (pid_n - s6 - 1)
        idx7 = s7 * N - (s7 * (s7 + 1)) // 2 + (pid_n - s7 - 1)
        xj0 = tl.load(x_ptr + (j0 + 0) * stride_x + m_offsets, mask=m_mask, other=0.0).to(tl.float32)
        xj1 = tl.load(x_ptr + (j0 + 1) * stride_x + m_offsets, mask=m_mask, other=0.0).to(tl.float32)
        xj2 = tl.load(x_ptr + (j0 + 2) * stride_x + m_offsets, mask=m_mask, other=0.0).to(tl.float32)
        xj3 = tl.load(x_ptr + (j0 + 3) * stride_x + m_offsets, mask=m_mask, other=0.0).to(tl.float32)
        xj4 = tl.load(x_ptr + (j0 + 4) * stride_x + m_offsets, mask=m_mask, other=0.0).to(tl.float32)
        xj5 = tl.load(x_ptr + (j0 + 5) * stride_x + m_offsets, mask=m_mask, other=0.0).to(tl.float32)
        xj6 = tl.load(x_ptr + (j0 + 6) * stride_x + m_offsets, mask=m_mask, other=0.0).to(tl.float32)
        xj7 = tl.load(x_ptr + (j0 + 7) * stride_x + m_offsets, mask=m_mask, other=0.0).to(tl.float32)
        g0 = tl.load(grad_ptr + idx0).to(tl.float32)
        g1 = tl.load(grad_ptr + idx1).to(tl.float32)
        g2 = tl.load(grad_ptr + idx2).to(tl.float32)
        g3 = tl.load(grad_ptr + idx3).to(tl.float32)
        g4 = tl.load(grad_ptr + idx4).to(tl.float32)
        g5 = tl.load(grad_ptr + idx5).to(tl.float32)
        g6 = tl.load(grad_ptr + idx6).to(tl.float32)
        g7 = tl.load(grad_ptr + idx7).to(tl.float32)
        d0 = tl.load(pdist_ptr + idx0).to(tl.float32)
        d1 = tl.load(pdist_ptr + idx1).to(tl.float32)
        d2 = tl.load(pdist_ptr + idx2).to(tl.float32)
        d3 = tl.load(pdist_ptr + idx3).to(tl.float32)
        d4 = tl.load(pdist_ptr + idx4).to(tl.float32)
        d5 = tl.load(pdist_ptr + idx5).to(tl.float32)
        d6 = tl.load(pdist_ptr + idx6).to(tl.float32)
        d7 = tl.load(pdist_ptr + idx7).to(tl.float32)
        diff0 = x_vals - xj0
        diff1 = x_vals - xj1
        diff2 = x_vals - xj2
        diff3 = x_vals - xj3
        diff4 = x_vals - xj4
        diff5 = x_vals - xj5
        diff6 = x_vals - xj6
        diff7 = x_vals - xj7
        acc0 += tl.where(d0 != 0.0, diff0 * g0 / d0, 0.0)
        acc1 += tl.where(d1 != 0.0, diff1 * g1 / d1, 0.0)
        acc2 += tl.where(d2 != 0.0, diff2 * g2 / d2, 0.0)
        acc3 += tl.where(d3 != 0.0, diff3 * g3 / d3, 0.0)
        acc4 += tl.where(d4 != 0.0, diff4 * g4 / d4, 0.0)
        acc5 += tl.where(d5 != 0.0, diff5 * g5 / d5, 0.0)
        acc6 += tl.where(d6 != 0.0, diff6 * g6 / d6, 0.0)
        acc7 += tl.where(d7 != 0.0, diff7 * g7 / d7, 0.0)

    for j in range(nmain2, pid_n):
        xj_vals = tl.load(x_ptr + j * stride_x + m_offsets, mask=m_mask, other=0.0).to(
            tl.float32
        )
        diff = x_vals - xj_vals
        pdist_idx = j * N - (j * (j + 1)) // 2 + (pid_n - j - 1)
        g = tl.load(grad_ptr + pdist_idx).to(tl.float32)
        dist = tl.load(pdist_ptr + pdist_idx).to(tl.float32)
        acc0 += tl.where(dist != 0.0, diff * g / dist, 0.0)

    acc = ((acc0 + acc1) + (acc2 + acc3)) + ((acc4 + acc5) + (acc6 + acc7))
    tl.store(out_ptr_row + m_offsets, acc.to(out_ptr.dtype.element_ty), mask=m_mask)


@libentry()
@triton.jit
def _pdist_backward_p1_kernel(
    grad_ptr,
    x_ptr,
    out_ptr,
    N,
    M,
    stride_x,
    stride_grad_out,
    BLOCK_M: tl.constexpr,
):
    """Backward kernel for p=1 case (L1 norm)."""
    pid_n = tle.program_id(1)
    pid_m = tle.program_id(0)

    row_offset = pid_n * stride_x
    x_ptr_row = x_ptr + row_offset
    out_ptr_row = out_ptr + pid_n * stride_grad_out

    m_offsets = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    m_mask = m_offsets < M

    x_vals = tl.load(x_ptr_row + m_offsets, mask=m_mask, other=0.0).to(tl.float32)

    acc = tl.zeros([BLOCK_M], dtype=tl.float32)

    # Pairs where this row is first (i, j) with i < j
    for j in range(pid_n + 1, N):
        xj_offset = j * stride_x
        xj_vals = tl.load(x_ptr + xj_offset + m_offsets, mask=m_mask, other=0.0).to(
            tl.float32
        )

        diff = x_vals - xj_vals
        sign = tl.where(diff > 0, 1.0, tl.where(diff < 0, -1.0, 0.0))

        pdist_idx = pid_n * N - (pid_n * (pid_n + 1)) // 2 + (j - pid_n - 1)
        g = tl.load(grad_ptr + pdist_idx).to(tl.float32)

        acc += g * sign

    # Pairs where this row is second (j, i) with j < i
    for j in range(0, pid_n):
        xj_offset = j * stride_x
        xj_vals = tl.load(x_ptr + xj_offset + m_offsets, mask=m_mask, other=0.0).to(
            tl.float32
        )

        diff = x_vals - xj_vals
        sign = tl.where(diff > 0, 1.0, tl.where(diff < 0, -1.0, 0.0))

        pdist_idx = j * N - (j * (j + 1)) // 2 + (pid_n - j - 1)
        g = tl.load(grad_ptr + pdist_idx).to(tl.float32)

        acc += g * sign

    tl.store(out_ptr_row + m_offsets, acc.to(out_ptr.dtype.element_ty), mask=m_mask)


@libentry()
@triton.jit
def _pdist_backward_general_kernel(
    grad_ptr,
    x_ptr,
    pdist_ptr,
    out_ptr,
    N,
    M,
    p_val,
    stride_x,
    stride_grad_out,
    BLOCK_M: tl.constexpr,
):
    """Backward kernel for general p value."""
    pid_n = tle.program_id(1)
    pid_m = tle.program_id(0)

    row_offset = pid_n * stride_x
    x_ptr_row = x_ptr + row_offset
    out_ptr_row = out_ptr + pid_n * stride_grad_out

    m_offsets = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    m_mask = m_offsets < M

    x_vals = tl.load(x_ptr_row + m_offsets, mask=m_mask, other=0.0).to(tl.float32)

    acc = tl.zeros([BLOCK_M], dtype=tl.float32)

    # Pairs where this row is first (i, j) with i < j
    for j in range(pid_n + 1, N):
        xj_offset = j * stride_x
        xj_vals = tl.load(x_ptr + xj_offset + m_offsets, mask=m_mask, other=0.0).to(
            tl.float32
        )

        diff = x_vals - xj_vals
        abs_diff = tl.abs(diff)
        sign = tl.where(diff > 0, 1.0, tl.where(diff < 0, -1.0, 0.0))

        pdist_idx = pid_n * N - (pid_n * (pid_n + 1)) // 2 + (j - pid_n - 1)
        g = tl.load(grad_ptr + pdist_idx).to(tl.float32)
        c = tl.load(pdist_ptr + pdist_idx).to(tl.float32)

        safe_c = tl.where(c == 0.0, 1.0, c)
        ratio = abs_diff / safe_c

        # Compute ratio^(p-1) using exp and log
        safe_ratio = tl.where(ratio == 0.0, 0.0, ratio)
        log_ratio = tl.where(safe_ratio > 0.0, tl.log(safe_ratio), 0.0)
        powered = tl.where(safe_ratio > 0.0, tl.exp((p_val - 1.0) * log_ratio), 0.0)

        contrib = tl.where(c == 0.0, 0.0, g * sign * powered)
        acc += contrib

    # Pairs where this row is second (j, i) with j < i
    for j in range(0, pid_n):
        xj_offset = j * stride_x
        xj_vals = tl.load(x_ptr + xj_offset + m_offsets, mask=m_mask, other=0.0).to(
            tl.float32
        )

        diff = x_vals - xj_vals
        abs_diff = tl.abs(diff)
        sign = tl.where(diff > 0, 1.0, tl.where(diff < 0, -1.0, 0.0))

        pdist_idx = j * N - (j * (j + 1)) // 2 + (pid_n - j - 1)
        g = tl.load(grad_ptr + pdist_idx).to(tl.float32)
        c = tl.load(pdist_ptr + pdist_idx).to(tl.float32)

        safe_c = tl.where(c == 0.0, 1.0, c)
        ratio = abs_diff / safe_c

        safe_ratio = tl.where(ratio == 0.0, 0.0, ratio)
        log_ratio = tl.where(safe_ratio > 0.0, tl.log(safe_ratio), 0.0)
        powered = tl.where(safe_ratio > 0.0, tl.exp((p_val - 1.0) * log_ratio), 0.0)

        contrib = tl.where(c == 0.0, 0.0, g * sign * powered)
        acc += contrib

    tl.store(out_ptr_row + m_offsets, acc.to(out_ptr.dtype.element_ty), mask=m_mask)


@libentry()
@triton.jit
def _pdist_backward_inf_kernel(
    grad_ptr,
    x_ptr,
    pdist_ptr,
    out_ptr,
    N,
    M,
    stride_x,
    stride_grad_out,
    BLOCK_M: tl.constexpr,
):
    """Backward kernel for p=inf case."""
    pid_n = tle.program_id(1)
    pid_m = tle.program_id(0)

    row_offset = pid_n * stride_x
    x_ptr_row = x_ptr + row_offset
    out_ptr_row = out_ptr + pid_n * stride_grad_out

    m_offsets = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    m_mask = m_offsets < M

    x_vals = tl.load(x_ptr_row + m_offsets, mask=m_mask, other=0.0).to(tl.float32)

    acc = tl.zeros([BLOCK_M], dtype=tl.float32)

    # Pairs where this row is first (i, j) with i < j
    for j in range(pid_n + 1, N):
        xj_offset = j * stride_x
        xj_vals = tl.load(x_ptr + xj_offset + m_offsets, mask=m_mask, other=0.0).to(
            tl.float32
        )

        diff = x_vals - xj_vals
        abs_diff = tl.abs(diff)

        pdist_idx = pid_n * N - (pid_n * (pid_n + 1)) // 2 + (j - pid_n - 1)
        g = tl.load(grad_ptr + pdist_idx).to(tl.float32)
        c = tl.load(pdist_ptr + pdist_idx).to(tl.float32)

        is_max = tl.where(abs_diff == c, 1.0, 0.0)
        sign = tl.where(diff > 0, 1.0, tl.where(diff < 0, -1.0, 0.0))

        acc += g * sign * is_max

    # Pairs where this row is second (j, i) with j < i
    for j in range(0, pid_n):
        xj_offset = j * stride_x
        xj_vals = tl.load(x_ptr + xj_offset + m_offsets, mask=m_mask, other=0.0).to(
            tl.float32
        )

        diff = x_vals - xj_vals
        abs_diff = tl.abs(diff)

        pdist_idx = j * N - (j * (j + 1)) // 2 + (pid_n - j - 1)
        g = tl.load(grad_ptr + pdist_idx).to(tl.float32)
        c = tl.load(pdist_ptr + pdist_idx).to(tl.float32)

        is_max = tl.where(abs_diff == c, 1.0, 0.0)
        sign = tl.where(diff > 0, 1.0, tl.where(diff < 0, -1.0, 0.0))

        acc += g * sign * is_max

    tl.store(out_ptr_row + m_offsets, acc.to(out_ptr.dtype.element_ty), mask=m_mask)


def _pdist_backward(grad, x, p, pdist):
    """Compute gradient of pdist forward pass."""
    logger.debug("GEMS _PDIST_BACKWARD")

    assert x.ndim == 2, "pdist only supports 2D input"
    assert x.dtype == torch.float32, "_pdist_backward only supports float32"
    N = x.shape[0]
    M = x.shape[1]

    grad = grad.contiguous()
    x = x.contiguous()
    pdist = pdist.contiguous()

    out = torch.empty_like(x)

    BLOCK_M = min(triton.next_power_of_2(M), _MAX_BLOCK_M)
    grid = (triton.cdiv(M, BLOCK_M), N)

    with torch_device_fn.device(x.device):
        if p == 2.0:
            _pdist_backward_p2_kernel[grid](
                grad,
                x,
                pdist,
                out,
                N,
                M,
                x.stride(0),
                out.stride(0),
                BLOCK_M=BLOCK_M,
            )
        elif p == 1.0:
            _pdist_backward_p1_kernel[grid](
                grad,
                x,
                out,
                N,
                M,
                x.stride(0),
                out.stride(0),
                BLOCK_M=BLOCK_M,
            )
        elif math.isinf(p):
            _pdist_backward_inf_kernel[grid](
                grad,
                x,
                pdist,
                out,
                N,
                M,
                x.stride(0),
                out.stride(0),
                BLOCK_M=BLOCK_M,
            )
        else:
            _pdist_backward_general_kernel[grid](
                grad,
                x,
                pdist,
                out,
                N,
                M,
                p,
                x.stride(0),
                out.stride(0),
                BLOCK_M=BLOCK_M,
            )

    return out
