# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.ops.rrelu_ import _rrelu_eval_
from flag_gems.runtime import torch_device_fn
from flag_gems.utils.random_utils import (
    philox_backend_seed_offset,
    uint_to_uniform_float,
)

logger = logging.getLogger(__name__)

TRAIN_BLOCK = 1024


@triton.jit(do_not_specialize=["lower", "upper", "philox_seed", "philox_offset"])
def rrelu_train_kernel(
    x_ptr,
    out_ptr,
    n_elements,
    lower,
    upper,
    philox_seed,
    philox_offset,
    BLOCK: tl.constexpr,
):
    philox_seed = philox_seed.to(tl.int64)
    philox_offset = philox_offset.to(tl.int64)
    c0 = (philox_offset & 0xFFFFFFFF).to(tl.uint32)
    c1 = ((philox_offset >> 32) & 0xFFFFFFFF).to(tl.uint32)

    offsets = tl.program_id(0) * BLOCK + tl.arange(0, BLOCK)
    c0 += offsets.to(tl.uint32)
    _O = c0 * 0
    r0, r1, r2, r3 = tl.philox(philox_seed, c0, c1, _O, _O)
    u0 = uint_to_uniform_float(r0)

    mask = offsets < n_elements
    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)

    lower_f = lower.to(tl.float32)
    upper_f = upper.to(tl.float32)
    x_f32 = x.to(tl.float32)
    slope = lower_f + u0 * (upper_f - lower_f)
    out = tl.where(x_f32 >= 0, x_f32, x_f32 * slope)
    tl.store(out_ptr + offsets, out.to(x.dtype), mask=mask)


def _rrelu_train_(A, lower, upper, generator=None):
    n_elements = A.numel()
    if n_elements == 0:
        return A
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK"]),)
    philox_seed, philox_offset = philox_backend_seed_offset(
        n_elements, generator=generator
    )
    with torch_device_fn.device(A.device):
        rrelu_train_kernel[grid](
            A,
            A,
            n_elements,
            float(lower),
            float(upper),
            philox_seed,
            philox_offset,
            BLOCK=TRAIN_BLOCK,
        )
    return A


def rrelu_(
    A,
    lower=0.125,
    upper=0.33333333333333331,
    training=False,
    generator=None,
):
    logger.debug("GEMS_KUNLUNXIN RRELU_")
    if training:
        return _rrelu_train_(A, lower, upper, generator)
    return _rrelu_eval_(A, lower, upper)
